version: "3.6"
services:
  web:
    container_name: express_app
    image: express_app
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    entrypoint: ["/bin/sh", "/code/initialize.sh"]
    ports:
     - "3000:3000"

    working_dir: /code
